name: simenang_krpg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  web_socket_channel: ^2.4.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
